server:
  port: '@server.port@'
  rest:
    port: '@server.rest.port@'
    endpoint: ch-manager
management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
---
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
riak:
  address: localhost
  port: 8087
  bucket: wblist

retry:
  timeout: 2000
  max.attempts: 3

kafka:
  bootstrap.servers: "localhost:29092"
  wblist.topic:
    command: "wb-list-command"
    event.sink: "wb-list-event-sink"
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
