server.port: @server.port@
management.security.flag: false
spring.application.name: @project.name@
info.version: @project.version@
info.stage: dev

management.metrics.export.statsd:
  flavor: etsy

riak:
  address: localhost
  port: 8087

kafka:
  bootstrap.servers: "localhost:29092"
  wblist.topic: "wblist"